name: Terraform CI

on:
    push:
        branches:
            - master

permissions:
    contents: read

jobs:
    terraform:
        runs-on: ubuntu-latest

        steps:
            # Step 1: Checkout the code
            - name: Checkout code
              uses: actions/checkout@v3

            # Step 2: Set AWS credentials from repo secrets
            - name: Set AWS Credentials
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              run: |
                  # Verify the credentials are set correctly
                  echo "AWS_ACCESS_KEY_ID is set."
                  aws sts get-caller-identity  # This will print the current AWS identity

            # Step 3: Set up Terraform
            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v2
              with:
                  terraform_version: 1.5.0

            # Step 4: Pull .tfvars from S3
            - name: Pull .tfvars from S3
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              run: |
                  aws s3 cp s3://terraform-tfvars-s3-bucket-lab1/dev.tfvars ./dev.tfvars --region ap-southeast-1

            # Step 5: Terraform Init
            - name: Terraform Init
              run: terraform init

            # Step 6: Terraform Plan
            - name: Terraform Plan
              run: terraform plan -var-file="dev.tfvars"

            # Step 7: Terraform Apply
            - name: Terraform Apply
              if: github.event_name == 'push'
              run: terraform apply -var-file="dev.tfvars" -auto-approve
